const modifiers = [
  'wet', 'chilled', 'frozen',
  'amber', 'oldamber', 'ancientamber',
  'verdant', 'sundried', 'paradisal',
  'clay', 'sandy', 'ceramic',
  'pollinated', 'honeyglazed',
  'choc', 'moonlit', 'bloodlit', 'windstruck', 'twisted',
  'burnt', 'cooked', 'fried',
  'heavenly', 'cloudtouched', 'plasma', 'drenched',
  'zomb', 'molten',
  'tempestuous',
  'friendbound',
  'infected',
  'aurora',
  'alienlike', 'galactic', 'celestial', 'shocked',
  'disco', 'meteoric',
  'voidtouched',
  'dawnbound',
  'tranquil', 'chakra', 'toxic', 'radioactive'
];

const modifierLabels = {
  wet: 'Wet 2X',
  chilled: 'Chilled 2X',
  frozen: 'Frozen 10X',
  amber: 'Amber 10X',
  oldamber: 'OldAmber 20X',
  ancientamber: 'Ancient Amber 50X',
  verdant: 'Verdant 4X',
  sundried: 'Sundried 85X',
  paradisal: 'Paradisal 100X',
  clay: 'Clay 3X',
  sandy: 'Sandy 3X',
  ceramic: 'Ceramic 30X',
  pollinated: 'Pollinated 3X',
  honeyglazed: 'Honeyglazed 5X',
  choc: 'Choc 2X',
  moonlit: 'Moonlit 2X',
  bloodlit: 'Bloodlit 4X',
  windstruck: 'Windstruck 2X',
  twisted: 'Twisted 2X',
  burnt: 'Burnt 4X',
  cooked: 'Cooked 10X',
  fried: 'Fried 8X',
  heavenly: 'Heavenly 5X',
  cloudtouched: 'Cloudtouched 5X',
  plasma: 'Plasma 5X',
  drenched: 'Drenched 5X',
  zomb: 'Zombified 25X',
  molten: 'Molten 25X',
  tempestuous: 'Tempestuous 12X',
  friendbound: 'Friendbound 70X',
  infected: 'Infected 75X',
  aurora: 'Aurora 90X',
  alienlike: 'Alienlike 100X',
  galactic: 'Galactic 120X',
  celestial: 'Celestial 120X',
  shocked: 'Shocked 100X',
  disco: 'Disco 125X',
  meteoric: 'Meteoric 125X',
  voidtouched: 'Voidtouched 135X',
  dawnbound: 'Dawnbound 150X',
  tranquil: 'Tranquil 20X',
  chakra: 'Chakra 8X',
  toxic: 'Toxic 12X',
  radioactive: 'Radioactive 80X'
};

const fruitTypes = [
  { id: 'rainbow', label: 'Rainbow 50X' },
  { id: 'gold', label: 'Gold 20X' }
];
