const modifiers = [
  'wet', 'chilled',
  'disco', 'choc', 'bloodlit', 'heavenly', 'celestial', 'moonlit',
  'frozen', 'zomb', 'shocked', 'plasma',
  'voidtouched', 'pollinated', 'honeyglazed',
  'burnt', 'cooked', 'dawnbound', 'meteoric', 'molten',
  'alienlike', 'sundried', 'galactic', 'windstruck', 'paradisal', 'twisted', 'verdant',
  'aurora', 'drenched',
  'cloudtouched', 'fried', 'sandy',
  'amber', 'oldamber', 'ancientamber', 'clay', 'ceramic',
  'friendbound', 'tempestuous', 'infected'
];
const modifierLabels = {
  wet: 'Wet 2X',
  chilled: 'Chilled 2X',
  disco: 'Disco 125X',
  choc: 'Choc 2X',
  bloodlit: 'Bloodlit 4X',
  heavenly: 'Heavenly 5X',
  celestial: 'Celestial 120X',
  moonlit: 'Moonlit 2X',
  frozen: 'Frozen 10X',
  zomb: 'Zombified 25X',
  shocked: 'Shocked 100X',
  plasma: 'Plasma 5X',
  voidtouched: 'Voidtouched 135X',
  pollinated: 'Pollinated 3X',
  honeyglazed: 'Honeyglazed 5X',
  burnt: 'Burnt 4X',
  cooked: 'Cooked 10X',
  dawnbound: 'Dawnbound 150X',
  meteoric: 'Meteoric 125X',
  molten: 'Molten 25X',
  alienlike: 'Alienlike 100X',
  sundried: 'Sundried 85X',
  galactic: 'Galactic 120X',
  windstruck: 'Windstruck 2X',
  paradisal: 'Paradisal 100X',
  twisted: 'Twisted 2X',
  verdant: 'Verdant 4X',
  aurora: 'Aurora 90X',
  drenched: 'Drenched 5X',
  cloudtouched: 'Cloudtouched 5X',
  fried: 'Fried 8X',
  sandy: 'Sandy 3X',
  amber: 'Amber 10X',
  oldamber: 'OldAmber 20X',
  ancientamber: 'Ancient Amber 50X',
  clay: 'Clay 3X',
  ceramic: 'Ceramic 30X',
  friendbound: 'Friendbound 70X',
  tempestuous: 'Tempestuous 12X',
  infected: 'Infected 75X'
};
const fruitTypes = [
  { id: 'rainbow', label: 'Rainbow 50X' },
  { id: 'gold', label: 'Gold 20X' }
];
