const plantLabels = {
  carrot: "Carrot",
  strawberry: "Strawberry",
  blueberry: "Blueberry",
  orangetulip: "Orange Tulip",
  tomato: "Tomato",
  corn: "Corn",
  daffodil: "Daffodil",
  watermelon: "Watermelon",
  pumpkin: "Pumpkin",
  apple: "Apple",
  bamboo: "Bamboo",
  coconut: "Coconut",
  cactus: "Cactus",
  dragonfruit: "Dragon Fruit",
  mango: "Mango",
  grape: "Grape",
  mushroom: "Mushroom",
  pepper: "Pepper",
  cacao: "Cacao",
  beanstalk: "Beanstalk",
  nightshade: "Nightshade",
  mint: "Mint",
  glowshroom: "Glowshroom",
  moonmelon: "Moon Melon",
  starfruit: "Star Fruit",
  moonflower: "Moon Flower",
  bloodbanana: "Blood Banana",
  moonglow: "Moonglow",
  moonblossom: "Moon Blossom",
  celestiberry: "Celestiberry",
  moonmango: "Moon Mango",
  candyblossom: "Candy Blossom",
  easteregg: "Easter Egg",
  raspberry: "Raspberry",
  pear: "Pear",
  peach: "Peach",
  cranberry: "Cranberry",
  durian: "Durian",
  eggplant: "Eggplant",
  papaya: "Papaya",
  banana: "Banana",
  passionfruit: "Passionfruit",
  soulfruit: "Soul Fruit",
  hive: "Hive Fruit",
  rose: "Rose",
  foxglove: "Foxglove",
  purpledahlia: "Purple Dahlia",
  lilac: "Lilac",
  sunflower: "Sunflower",
  pinklily: "Pink Lily",
  nectarine: "Nectarine",
  emberlily: "Ember Lily",
  nectarshade: "Nectarshade",
  manuka: "Manuka",
  dandelion: "Dandelion",
  lumira: "Lumira",
  honeysuckle: "Honeysuckle",
  beebalm: "Beebalm",
  nectarthorn: "Nectar Thorn",
  suncoil: "Suncoil",
  crocus: "Crocus",
  succulent: "Succulent",
  violetcorn: "Violet Corn",
  bendboo: "Bendboo",
  cocovine: "Cocovine",
  dragonpepper: "Dragon Pepper",
  cauliflower: "Cauliflower",
  greenapple: "Green Apple",
  avocado: "Avocado",
  pineapple: "Pineapple",
  kiwi: "Kiwi",
  bellpepper: "Bell Pepper",
  pricklypear: "Prickly Pear",
  loquat: "Loquat",
  feijoa: "Feijoa",
  sugarapple: "Sugar Apple",
  burningbud: "Burning Bud",
  wildcarrot: "Wild Carrot",
  cantaloupe: "Cantaloupe",
  parasolflower: "Parasol Flower",
  rosydelight: "Rosy Delight",
  elephantears: "Elephant Ears",
  stonebite: "Stonebite",
  paradisepetal: "Paradise Petal",
  horneddinoshroom: "Horned Dinoshroom",
  boneboo: "Boneboo",
  fireflyfern: "Firefly Fern",
  fossilight: "Fossilight",
  boneblossom: "Bone Blossom"
};

const plantImages = {
  carrot: "img/carrot.png",
  strawberry: "img/strawberry.png",
  blueberry: "img/blueberry.png",
  orangetulip: "img/orangetulip.png",
  tomato: "img/tomato.png",
  corn: "img/corn.png",
  daffodil: "img/daffodil.png",
  watermelon: "img/watermelon.png",
  pumpkin: "img/pumpkin.png",
  apple: "img/apple.png",
  bamboo: "img/bamboo.png",
  coconut: "img/coconut.png",
  cactus: "img/cactus.png",
  dragonfruit: "img/dragonfruit.png",
  mango: "img/mango.png",
  grape: "img/grape.png",
  mushroom: "img/mushroom.png",
  pepper: "img/pepper.png",
  cacao: "img/cacao.png",
  beanstalk: "img/beanstalk.png",
  nightshade: "img/nightshade.png",
  mint: "img/mint.png",
  glowshroom: "img/glowshroom.png",
  moonmelon: "img/moonmelon.png",
  starfruit: "img/starfruit.png",
  moonflower: "img/moonflower.png",
  bloodbanana: "img/bloodbanana.png",
  moonglow: "img/moonglow.png",
  moonblossom: "img/moonblossom.png",
  celestiberry: "img/celestiberry.png",
  moonmango: "img/moonmango.png",
  candyblossom: "img/candyblossom.png",
  easteregg: "img/easteregg.png",
  raspberry: "img/raspberry.png",
  pear: "img/pear.png",
  peach: "img/peach.png",
  cranberry: "img/cranberry.png",
  durian: "img/durian.png",
  eggplant: "img/eggplant.png",
  papaya: "img/papaya.png",
  banana: "img/banana.png",
  passionfruit: "img/passionfruit.png",
  soulfruit: "img/soulfruit.png",
  hive: "img/hive.png",
  rose: "img/rose.png",
  foxglove: "img/foxglove.png",
  purpledahlia: "img/purpledahlia.png",
  lilac: "img/lilac.png",
  sunflower: "img/sunflower.png",
  pinklily: "img/pinklily.png",
  nectarine: "img/nectarine.png",
  emberlily: "img/emberlily.png",
  nectarshade: "img/nectarshade.png",
  manuka: "img/manuka.png",
  dandelion: "img/dandelion.png",
  lumira: "img/lumira.png",
  honeysuckle: "img/honeysuckle.png",
  beebalm: "img/beebalm.png",
  nectarthorn: "img/nectarthorn.png",
  suncoil: "img/suncoil.png",
  crocus: "img/crocus.png",
  succulent: "img/succulent.png",
  violetcorn: "img/violetcorn.png",
  bendboo: "img/bendboo.png",
  cocovine: "img/cocovine.png",
  dragonpepper: "img/dragonpepper.png",
  cauliflower: "img/cauliflower.png",
  greenapple: "img/greenapple.png",
  avocado: "img/avocado.png",
  pineapple: "img/pineapple.png",
  kiwi: "img/kiwi.png",
  bellpepper: "img/bellpepper.png",
  pricklypear: "img/pricklypear.png",
  loquat: "img/loquat.png",
  feijoa: "img/feijoa.png",
  sugarapple: "img/sugarapple.png",
  burningbud: "img/burningbud.png",
  wildcarrot: "img/wildcarrot.png",
  cantaloupe: "img/cantaloupe.png",
  parasolflower: "img/parasolflower.png",
  rosydelight: "img/rosydelight.png",
  elephantears: "img/elephantears.png",

  stonebite: "img/stonebite.png",
  paradisepetal: "img/paradisepetal.png",
  horneddinoshroom: "img/horneddinoshroom.png",
  boneboo: "img/boneboo.png",
  fireflyfern: "img/fireflyfern.png",
  fossilight: "img/fossilight.png",
  boneblossom: "img/boneblossom.png"
};

const plantMinWeights = {
  easteregg: 2.85,
  moonflower: 1.90,
  starfruit: 2.85,
  pepper: 4.75,
  grape: 2.85,
  nightshade: 0.48,
  mint: 0.95,
  glowshroom: 0.70,
  bloodbanana: 1.42,
  beanstalk: 9.5,
  coconut: 13.31,
  candyblossom: 2.85,
  carrot: 0.24,
  strawberry: 0.29,
  blueberry: 0.17,
  orangetulip: 0.0499,
  tomato: 0.44,
  daffodil: 0.16,
  watermelon: 7.3,
  pumpkin: 6.9,
  mushroom: 25.9,
  bamboo: 3.80,
  apple: 2.85,
  corn: 1.90,
  cactus: 6.65,
  cranberry: 0.95,
  moonmelon: 6.84,
  pear: 2.85,
  durian: 7.6,
  peach: 1.90,
  cacao: 7.6,
  moonglow: 6.65,
  dragonfruit: 11.38,
  mango: 14.28,
  moonblossom: 2.86,
  raspberry: 0.71,
  eggplant: 4.75,
  papaya: 2.86,
  celestiberry: 1.90,
  moonmango: 14.25,
  banana: 1.425,
  passionfruit: 2.867,
  soulfruit: 23.75,
  hive: 5.9,
  rose: 0.95,
  foxglove: 1.9,
  purpledahlia: 11.4,
  lilac: 2.846,
  sunflower: 14.23,
  pinklily: 4.3,
  nectarine: 2.807,
  emberlily: 11.40,
  nectarshade: 0.75,
  manuka: 0.29,
  dandelion: 3.79,
  lumira: 5.69,
  honeysuckle: 11.40,
  beebalm: 0.940,
  nectarthorn: 5.760,
  suncoil: 9.500,
  crocus: 0.285,
  succulent: 4.750,
  violetcorn: 2.850,
  bendboo: 17.090,
  cocovine: 13.300,
  dragonpepper: 5.690,
  cauliflower: 4.740,
  greenapple: 2.850,
  avocado: 3.320,
  pineapple: 2.850,
  kiwi: 4.750,
  bellpepper: 7.610,
  pricklypear: 6.650,
  loquat: 6.170,
  feijoa: 9.500,
  sugarapple: 8.550,
  burningbud: 11.400,
  wildcarrot: 0.286,
  cantaloupe: 5.220,
  parasolflower: 5.700,
  rosydelight: 9.500,
  elephantears: 17.100,
  stonebite: 0.940,
  paradisepetal: 2.850,
  horneddinoshroom: 4.940,
  boneboo: 14.500,
  fireflyfern: 4.770,
  fossilight: 3.790,
  boneblossom: 2.30
};